export const CLICK = 'CLICK';

export const CLEAR = 'CLEAR';

export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_FUFILLED = 'FETCH_USER_FUFILLED';


export const FETCH_HACKER_NEWS ='FETCH_HACKER_NEWS';
export const FETCH_HACKER_NEWS_FUFILLED = 'FETCH_HACKER_NEWS_FUFILLED'


export const SEARCH_BEER = 'SEARCH_BEER'
export const SEARCH_BEER_FUFILLED = 'SEARCH_BEER_FUFILLED'
export const SEARCH_BEER_ERROR = 'SEARCH_BEER_ERROR';
export const CANCEL_SEARCH_BEER = 'CANCEL_SEARCH_BEER'
